services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: expensetrackerapp
      POSTGRES_PASSWORD: "kVcWb7G4SzAaMf7Cti4f3GG1ojcfRRL1"
    volumes:
      - expensetrackerapp_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "EJ7pMr_XGLUsq_BRZyFc8vSUY2W4fNv-"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: expensetrackerapp_test
      POSTGRES_PASSWORD: "UYJQkzFRjXQde78hwAuob5eey6tuVJTr"
    volumes:
      - expensetrackerapp_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "jcaCnPEpm4YJJrKe00GDHKoVULQOWkzX"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  expensetrackerapp_data:
  expensetrackerapp_test_data:
